<?php
/**
 * Created by PhpStorm.
 * User: Crazypeak
 * Date: 2017/10/22
 * Time: 23:54
 */

namespace app\admin\controller\information;

use app\admin\controller\Index;
use app\admin\model\ColumnModel;
use app\admin\model\GoodsModel;

class Goods extends Index
{
    public function _initialize()
    {
        $column_list = ColumnModel::getColumnUrlName(['status' => 1]);
        $this->assign('column_list', $column_list);

        return parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        $goods_page = GoodsModel::getGoodsPage();
        $this->assign('list', $goods_page);

        return $this->fetch('information/goodsList');
    }

    public function add()
    {
        if ($data = input('post.')) {
            if ($file = request()->file('img')) {
                $file_name       = $file->validate(['ext' => 'jpg,png'])->rule('uniqid')->move(ROOT_PATH . 'upload' .DS.  'goods')->getBasename();
                $data['img_url'] = '/upload/goods/' . $file_name;
            }

            $result = GoodsModel::addGoods($data);
            is_numeric($result) ? $this->success('操作成功', url('save', ['id' => $result])) : $this->error($result);
        }
    }

    public function save($id = null)
    {
        $goods = GoodsModel::getGoodsOne($id);
        $goods['detail'] = GoodsModel::getGoodsDetailList($id);
        $this->assign('goods', $goods);

        return $this->fetch('information/goodsSave');
    }

    public function del($id = null)
    {
        (!$id || !is_numeric($id)) && $this->error('参数错误');
        $result = GoodsModel::delGoods($id);
        $result ? $this->success('操作成功') : $this->error($result);
    }

    public function detailSave()
    {
        if ($data = input('post.')){
            if (isset($data['pid']) && $data['pid'] != 0 && $file = request()->file('detailImg')) {
                $file_name       = $file->validate(['ext' => 'jpg,png'])->rule('uniqid')->move(ROOT_PATH . 'upload' .DS.  'goods')->getBasename();
                $data['img_url'] = '/upload/goods/' . $file_name;
            }

            $result = GoodsModel::saveGoodsDetail($data);
            empty($result) ? $this->success('操作成功') : $this->error($result);
        }
    }

    public function detailDel($id = null)
    {
        (!$id || !is_numeric($id)) && $this->error('参数错误');
        $result = GoodsModel::delGoodsDetail($id);
        $result ? $this->success('操作成功') : $this->error($result);
    }
}