<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/6/20
 * Time: 17:28
 */

namespace app\admin\controller\information;

use app\admin\controller\Index;
use app\admin\model\GoodsModel;

class Product extends Index{


    public function _initialize()
    {
        $column_list = GoodsModel::getClassList();
        $this->assign('column_list', $column_list);

        return parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 批量上传
     */
    public function ajaxGoodsAdds(){
        if ($data = input('post.')){
//            var_dump($data);die();
            $result = GoodsModel::addGoodsArray($data['images'],$data['class_id']);
            empty($result) ? $this->success('操作成功') : $this->error($result);
        }else $this->error('无参数传入');
    }

    public function index()
    {
        $where = [];
        input('?class_id') && $where['class_id'] = input('class_id');

        $goods_page = GoodsModel::getGoodsPage($where);
        $this->assign('list', $goods_page);

        return $this->fetch('information/goodsList');
    }

    public function add()
    {
        if ($data = input('post.')) {
            if ($file = request()->file('img')) {
                $file_name       = $file->validate(['ext' => 'jpg,png'])->rule('uniqid')->move(ROOT_PATH . 'upload' .DS.  'goods')->getBasename();
                $data['img_url'] = '/upload/goods/' . $file_name;
            }

            $result = GoodsModel::addGoods($data);
            is_numeric($result) ? $this->success('操作成功', url('save', ['id' => $result])) : $this->error($result);
        }
    }

    public function save($id = null)
    {
        $goods = GoodsModel::getGoodsOne($id);
        $goods['detail_list'] = GoodsModel::getGoodsDetailList($id);
        $this->assign('goods', $goods);

        return $this->fetch('information/goodsSave');
    }

    public function del($id = null)
    {
        (!$id || !is_numeric($id)) && $this->error('参数错误');
        $result = GoodsModel::delGoods($id);
        $result ? $this->success('操作成功') : $this->error($result);
    }

    public function detailSave()
    {
        if ($data = input('post.')){
            if (isset($data['pid']) && $data['pid'] != 0 && $file = request()->file('detailImg')) {
                $file_name       = $file->validate(['ext' => 'jpg,png'])->rule('uniqid')->move(ROOT_PATH . 'upload' .DS.  'goods')->getBasename();
                $data['img_url'] = '/upload/goods/' . $file_name;
            }

            $result = GoodsModel::saveGoodsDetail($data);
            empty($result) ? $this->success('操作成功') : $this->error($result);
        }
    }

    public function detailDel($id = null)
    {
        (!$id || !is_numeric($id)) && $this->error('参数错误');
        $result = GoodsModel::delGoodsDetail($id);
        $result ? $this->success('操作成功') : $this->error($result);
    }

    /**
     * 前端输出，默认输出所有分类
     * @return mixed
     */
    public function classList($cid = 0)
    {
        $this->assign('cid',$cid);
        $class_list = GoodsModel::getClassList();
//        $this->assign('class_list', list_to_tree($class_list));
        $this->assign('class_list', $class_list);
        return $this->fetch('information/goodsClassList');
    }

    /**
     * 新增编辑商品分类
     * @param null $id
     * @return array|false|\PDOStatement|string|\think\Model
     */
    public function classEdit($id = null)
    {
        if ($data = input('post.')) {
            $result = GoodsModel::saveClass($data);
            empty($result) ? $this->success('操作成功') : $this->error($result);
        } else {
            $row = $id ? GoodsModel::getClassOne($id) : '';
            return $row;
        }
    }

    public function classDel($id = null)
    {
        (!$id || !is_numeric($id)) && $this->error('参数错误');

        $result = GoodsModel::delClass($id);

        empty($result) ? $this->success('操作成功') : $this->error($result);
    }
}