import '../public/static/css/iCheck/flat/blue.css';
import '../public/static/css/iCheck/line/blue.css';
import '../public/static/css/fontawesome/css/font-awesome.min.css';
import '../public/static/css/ionicons.min.css';
import '../public/static/css/sweetalert.css';
import '../public/static/css/bootstrap-spinner.min.css';
import '../public/static/css/select2.min.css';
import '../public/static/css/bootstrap-datepicker3.min.css';
import '../public/static/css/skin-blue.min.css';
import '../public/static/css/skin-green-light.min.css';
import '../public/static/css/bootstrap.min.css';
import '../public/static/css/AdminLTE.min.css';
import '../public/static/css/jquery.raty.css'
import '../public/static/css/style.css';
